openapi: 3.1.0
info:
  title: Kakao Trend Keyword Proxy API
  version: 1.0.1
  description: |
    Fetch trending keywords from Kakao through a proxy server. 
    This avoids CORS and credential issues by forwarding requests from a server hosted on Vercel.

servers:
  - url: https://kakao-proxy-server.vercel.app
    description: Vercel Proxy Server

paths:
  /api/kakao:
    get:
      operationId: getTrendKeywordsViaProxy
      summary: Get trending keywords via proxy
      description: Retrieves Daum's trending keywords using a fixed query: `?w=trend_keyword&random=2&n=100`.
      parameters:
        - name: w
          in: query
          required: true
          schema:
            type: string
            example: trend_keyword
        - name: random
          in: query
          required: true
          schema:
            type: integer
            example: 2
        - name: n
          in: query
          required: true
          schema:
            type: integer
            example: 100
      responses:
        '200':
          description: Successfully fetched trending keywords
          content:
            application/json:
              schema:
                type: object
                properties:
                  createdAt:
                    type: string
                    format: date-time
                  updatedAt:
                    type: string
                    format: date-time
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        keyword:
                          type: string
                        topic:
                          type: string
                        score:
                          type: number
